name: CMake CI (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**'
      - '!**.md'
      - '!documentation/**'
      - '!.vscode/**'
      - '!*.yml'
      - '!*.yaml'
      - '.github/workflows/ci-windows.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**'
      - '!**.md'
      - '!documentation/**'
      - '!.vscode/**'
      - '!*.yml'
      - '!*.yaml'
      - '.github/workflows/ci-windows.yml'

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        preset: [
          windows-clang-cl-debug,
          windows-msvc-release
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # windows-latest already has Ninja, clang-cl, and msvc environment
     
      - name: Configure CMake
        run: cmake --preset=${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset=${{ matrix.preset }} --verbose

      - name: Show files
        shell: pwsh
        working-directory: build/bin
        run: |
          Get-ChildItem
          if (Test-Path voices) {
            tree /A /F voices
          }
